# Generated by Django 4.0.2 on 2022-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UUID", models.UUIDField(unique=True)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "municipality",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "report_description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("reportByMunicipalityUser", models.BooleanField()),
            ],
        ),
    ]
