# Generated by Django 4.0.2 on 2022-03-01 10:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_alert", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trafficalert",
            name="id",
        ),
        migrations.AlterField(
            model_name="trafficalert",
            name="UUID",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
