# Generated by Django 4.0.2 on 2022-03-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_alert', '0004_remove_trafficalert_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trafficalert',
            old_name='localisation',
            new_name='localisation_description',
        ),
    ]
