# Generated by Django 4.0.2 on 2022-03-05 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_table', '0001_initial'),
        ('traffic_alert', '0006_trafficalert_localisation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficalert',
            name='alert_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alert_table.alerttable'),
        ),
    ]
