# Generated by Django 4.0.3 on 2022-03-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_alert", "0008_alter_trafficalert_lat_alter_trafficalert_lon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficalert",
            name="lat",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name="trafficalert",
            name="lon",
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
