# Generated by Django 4.0.2 on 2022-03-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("traffic_alert", "0007_trafficalert_alert_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lon", models.DecimalField(decimal_places=6, max_digits=9)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("poll_result", models.BooleanField()),
                (
                    "traffic_alert_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="traffic_alert.trafficalert",
                    ),
                ),
            ],
        ),
    ]
