# Generated by Django 4.0.2 on 2022-03-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('alert_type', models.CharField(max_length=30)),
                ('alert_subtype', models.CharField(max_length=30)),
            ],
        ),
    ]
